### ISSUE TITLE
line 103

### ISSUE THREAD

**Issue by 20m06** [20m06/Lasagna#1]
when code is running string "To uncover lasagna press U on your keyboard and press Enter: " always repeat two times

**Comment by ilyaev** [comment]
Try this method instead on line 104: user.uncover = kboard.next(); Looks like nextLine catch last 'enter' value.

**Comment by 20m06** [comment]
> Try this method instead on line 104: user.uncover = kboard.next(); Looks like nextLine catch last 'enter' value.

Yes, it helped.Thank you!
